---
abstract: 'Yet another DarkPAN manager.'
author:
  - 'tokuhirom <tokuhirom@gmail.com>'
build_requires:
  File::Which: 0
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OrePAN2
no_index:
  directory:
    - t
    - xt
    - tools
    - test-dist
provides:
  OrePAN2:
    file: lib/OrePAN2.pm
    version: 0.17
  OrePAN2::CLI::Indexer:
    file: lib/OrePAN2/CLI/Indexer.pm
  OrePAN2::CLI::Inject:
    file: lib/OrePAN2/CLI/Inject.pm
  OrePAN2::Index:
    file: lib/OrePAN2/Index.pm
  OrePAN2::Indexer:
    file: lib/OrePAN2/Indexer.pm
  OrePAN2::Injector:
    file: lib/OrePAN2/Injector.pm
requires:
  Archive::Extract: 0.68
  Archive::Tar: 0
  CPAN::Meta: 2.13156
  File::Temp: 0
  File::pushd: 0
  Getopt::Long: 2.39
  HTTP::Tiny: 0
  MetaCPAN::API: 0.43
  Parse::LocalDistribution: 0.01
  PerlIO::gzip: 0
  Pod::Usage: 0
  parent: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/tokuhirom/OrePAN2/issues
  homepage: https://github.com/tokuhirom/OrePAN2
  repository: git://github.com/tokuhirom/OrePAN2.git
version: 0.17
x_contributors:
  - 'Shoichi Kaji <skaji@outlook.com>'
  - 'Masahiro Honma <hiratara@cpan.org>'
  - 'Chad Granum <exodist7@gmail.com>'
  - 'Songmu <y.songmu@gmail.com>'
  - 'moznion <moznion@gmail.com>'
