---
abstract: 'Yet another DarkPAN manager.'
author:
  - 'tokuhirom <tokuhirom@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.2, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OrePAN2
no_index:
  directory:
    - t
    - xt
    - tools
    - test-dist
provides:
  OrePAN2:
    file: lib/OrePAN2.pm
    version: 0.02
  OrePAN2::CLI::Indexer:
    file: lib/OrePAN2/CLI/Indexer.pm
    version: 0
  OrePAN2::CLI::Inject:
    file: lib/OrePAN2/CLI/Inject.pm
    version: 0
  OrePAN2::Index:
    file: lib/OrePAN2/Index.pm
    version: 0
  OrePAN2::Indexer:
    file: lib/OrePAN2/Indexer.pm
    version: 0
  OrePAN2::Injector:
    file: lib/OrePAN2/Injector.pm
    version: 0
requires:
  Archive::Extract: 0.68
  Archive::Tar: 0
  CPAN::Meta: 0
  File::Temp: 0
  File::pushd: 0
  Getopt::Long: 0
  HTTP::Tiny: 0
  Module::Metadata: 0
  Parse::PMFile: 0
  PerlIO::gzip: 0
  Pod::Usage: 0
  parent: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/tokuhirom/OrePAN2/issues
  homepage: https://github.com/tokuhirom/OrePAN2
  repository: git://github.com/tokuhirom/OrePAN2.git
version: 0.02
